// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cunjmhluheowropvlksg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN1bmptaGx1aGVvd3JvcHZsa3NnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwOTIwNzgsImV4cCI6MjA2NDY2ODA3OH0.5TkMnR0hKekhCP0hbHGQv2sisFO5WY3Sppbl8ecOL9E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);